### ISSUE TITLE
Some functions still set up to pass SpiceCell object in as a pointer.

### ISSUE THREAD

**Issue by parkerjon** [AndrewAnnex/SpiceyPy#123]
Hello,
I just started implementing a SPICE system in a popular 3D animation package and switched over to SpiceyPy from PySPICE, as it seems to be more active.

I've run into an issue where trying to supply a SpiceCell object to spiceypy.spkobj causes the application to crash for some reason.  Probably because it expects a pointer, although to be honest I really don't know much about how the ctypes module works.

After a little investigation it looks like some functions have been modified to be more Pythonic by returning a new SpiceCell (such as bltfrm) and some haven't, such as spkobj. For that I modified wrapper.py to return a new object and it seemed to fix the crashing issue.

Is this something that should be fixed or am I using the API incorrectly somehow?
Thanks for all the hard work on this package!

**Comment by AndrewAnnex** [comment]
First of all, thanks for trying out the project. I am a little surprised that the unit tests wouldn't have caught the issue you were having, but the fix you made sounds reasonable. I would have to look at some example of your usage to see if you are using it wrong, but if you haven't yet please check out the unit tests for example usages for the function.

If you are willing to, consider posting a pull request with your changes (you will also need to update 3 units tests that use the function). I don't have a CLA yet, but considering it is a MIT licensed allready the general "do no evil" rules apply. Otherwise I can probably get to this later this week.

Thanks again!

**Comment by parkerjon** [comment]
Great, I haven't taken a look at the unit tests yet.  If that doesn't clear things up I'll take a closer look at the code and see what makes sense or not.

This is just a personal project at the moment so I don't mind also learning more about how the cspice code is being translated as a side-effect.

**Comment by parkerjon** [comment]
Hi Andrew, after looking at the unit test and modifying my code I was able to prevent the crash, thanks.

However I think I see now why I was confused.  I believe there may be a bit of inconsistency in the way  spkobj deals with SpiceCell objects, compared to other functions that are similar.  Take a look at the following definitions:
def ckobj(ck, ids=None)     :return: Set of ID codes of objects in CK file.
def bltfrm(frmcls, outSize=126)    :return: Set of ID codes of frames of the specified class.
def kplfrm(frmcls, cell_size=1000)    :return: Set of ID codes of frames of the specified class.
def spkobj(spk, ids):   No return type

I'd be happy to modify spkobj to match the behavior of ckobj, which is probably the closest in intent.

**Comment by AndrewAnnex** [comment]
glad to hear that was sorted, yeah the consistency could be better with those functions. If you post a PR I will happily review it otherwise I will probably take this on during the weekend.

**Comment by AndrewAnnex** [comment]
I think I resolved this issue for now, that I have fixed *all* consistency issues with the project :wink:

**Comment by parkerjon** [comment]
Great, I'll update my local copy and do some tests soon.  Thanks Andrew!

**Comment by AndrewAnnex** [comment]
closing issue
