### ISSUE TITLE
spicypy not found using conda install on all platforms

### ISSUE THREAD

**Issue by RossWilliamson** [AndrewAnnex/SpiceyPy#157]
Attempted to install via conda.  Following error given:

conda install -c https://conda.anaconda.org/andrewannex spiceypy
Fetching package metadata .........
Solving package specifications: .
Error: Package missing in current linux-64 channels: 
  - spiceypy

Anaconda version:

anaconda                  2.3.0                np19py27_0

**Comment by AndrewAnnex** [comment]
Hi Ross thanks for writing in, I had not tested the anaconda cloud install of spiceypy on linux so I might just need to upload another artifact to their website, but I won't be able to get to this for a day or two. 

That being said you can still install spiceypy using  `pip` instead of conda. Pip is included in your version of anaconda so you should be able to just run `pip install spiceypy`. 

let me know if that works for you

**Comment by AndrewAnnex** [comment]
so I started taking a look at this and it looks like I underestimated some of the complexities of conda. I will start work on conda files for linux and maybe macs. I will also probably update the documentation to emphasize installation using pip which is included in the miniconda and anaconda distributions.  @RossWilliamson if you are still having issues installing spiceypy using pip would work instead of using conda.

**Comment by AndrewAnnex** [comment]
So I have taken another look at this and the news is not so good. First of all I made a false assumption when I thought conda would fallback automatically to pip, this is not the case. 

From the start I also assumed most anaconda users were windows users (for some reason idk what). So I only made conda packages for windows as the build process is so complicated on windows. If a user has a mac or linux computer they have the tools out of the box to run the pip install with no other steps involved. 

To properly support Linux/Mac with conda I will need to do some work on my end to make sure I have build environments ready to go for linux/mac. I do this already with windows using appveyor, and I anticipate being able to do this also using travis ci. This will be a non trivial amount of work so it may take me a bit, but it may be a good excuse for me to sort out automatic artifact uploading.

@RossWilliamson I will make a ticket for myself relating to the eventual fix for this, but as it doesn't prevent you from installing spiceypy using pip I would claim that this isn't a critical issue.

**Comment by AndrewAnnex** [comment]
@RossWilliamson well it ended up not taking me all that long to sort this out. I now have conda packages built for 64 bit mac/linux for both python 2.7 and 3.5.

Let me know if that works for you. I will likely mark this issue as resolved in a day or two.

**Comment by AndrewAnnex** [comment]
closing this ticket as I think I have resolved it, I still have a little work to do with automated artifact deployment
