### ISSUE TITLE
Tutorial Problem

### ISSUE THREAD

**Issue by Rhys314** [AndrewAnnex/SpiceyPy#166]
Hello,

I've tried to follow the [Cassini position example](http://spiceypy.readthedocs.io/en/master/exampleone.html) but the first call to str2et throws a SPICE (NOLEAPSECONDS) error:

SpiceyError: 
====================================================================
Toolkit version: N0065

SPICE(NOLEAPSECONDS) --

The variable that points to the leapseconds (DELTET/DELTA_AT) could not be located in the kernel pool.  It is likely that the leapseconds kernel has not been loaded via the routine FURNSH.

str2et_c --> STR2ET --> TTRANS

====================================================================

I find this error odd as the [ste2et_c documentation](http://naif.jpl.nasa.gov/pub/naif/toolkit_docs/C/cspice/str2et_c.html) doesn't list SPICE(NOLEAPSECONDS) as a possible exception.  What I assume are the two other functions in the stack trace (STR2ET and TTRANS) have no documentation on the naif website.  You can find my attempt at the example [here](https://github.com/Rhys314/Test).  I am running 64-bit Python 3.5.2 on Windows 10 using a WinPython distribution.

**Comment by AndrewAnnex** [comment]
So I looked at your example repo and found that the issue is your meta kernel file, the first issue is that the `\begindata` needs to be on a new line above the `KERNELS_TO_LOAD`. I also updated the paths in the meta kernel to be relative to the python file like so:`cassini_kernel/naif0009.tls` for each of the kernels. After that it ran fine. You can print out how many kernels have been loaded by running running `spiceypy.ktotal("ALL")`, for your example before the fix it returned 1 (iirc) and after it returns 10. As for why that exception is not documented, I have no idea.  Hope that helps

**Comment by Rhys314** [comment]
Thanks for the help Andrew, works just fine now.
