### ISSUE TITLE
Installing on anaconda Python 3.4.4

### ISSUE THREAD

**Issue by vancesteven** [AndrewAnnex/SpiceyPy#168]
Here are the install command and output:
conda install -c https://conda.anaconda.org/andrewannex spiceypy
Fetching package metadata .........
Solving package specifications: ....

UnsatisfiableError: The following specifications were found to be in conflict:
- python 3.4*
- spiceypy
  Use "conda info <package>" to see the dependencies for each package.

**Comment by vancesteven** [comment]
pip also fails, but apparently for different reasons:
sudo -H pip install spiceypy
Collecting spiceypy
  Downloading spiceypy-1.1.0.tar.gz (213kB)
    100% |████████████████████████████████| 215kB 2.6MB/s 
    Complete output from command python setup.py egg_info:
    
    You have not agreed to the Xcode license agreements, please run 'xcodebuild -license' (for user-level acceptance) or 'sudo xcodebuild -license' (for system-wide acceptance) from within a Terminal window to review and agree to the Xcode license agreements.
    Error: cspice object file extraction failed with exit status: ('17664',)
    Unable to find CSPICE at /private/tmp/pip-build-z3cdopq1/spiceypy/cspice. Attempting to Download CSPICE For you:
    Gathering information...
    SYSTEM:    Mac
    PROCESSOR: i386
    MACHINE:   64bit
    Best option: MacIntel_OSX_AppleC_64bit
    URL:  https://naif.jpl.nasa.gov/pub/naif/misc/toolkit_N0065/C/MacIntel_OSX_AppleC_64bit/packages/cspice.tar.Z
    
    Downloading...
    Attempting to download spice...
    Unpacking... (this may take some time!)
    Host OS: Darwin
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-z3cdopq1/spiceypy/

**Comment by vancesteven** [comment]
pip also fails, but apparently for different reasons:

sudo -H pip install spiceypy
Collecting spiceypy
  Using cached spiceypy-1.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    gcc: warning: couldn’t understand kern.osversion ‘15.6.0
    ld: library not found for -ldylib1.o
    collect2: error: ld returned 1 exit status
    Error: compilation of shared spice.so build exit status: ('256',)
    Unable to find CSPICE at /private/tmp/pip-build-m8yfyywh/spiceypy/cspice. Attempting to Download CSPICE For you:
    Gathering information...
    SYSTEM:    Mac
    PROCESSOR: i386
    MACHINE:   64bit
    Best option: MacIntel_OSX_AppleC_64bit
    URL:  https://naif.jpl.nasa.gov/pub/naif/misc/toolkit_N0065/C/MacIntel_OSX_AppleC_64bit/packages/cspice.tar.Z
    
    Downloading...
    Attempting to download spice...
    Unpacking... (this may take some time!)
    Host OS: Darwin
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-m8yfyywh/spiceypy/

**Comment by AndrewAnnex** [comment]
ah so the issue here is that I dropped python 3.4 support. There is nothing technically preventing me from supporting python 3.4, but I wanted to reduce the CI build times. Is there anything preventing you from upgrading your anaconda to 4.0.0 or newer? If not I won't have time to do this until later in the week.

The pip install assumes you have accepted the Xcode license agreement. Run the command in the error output and it should work the second time (you may also need to run as sudo(.

**Comment by AndrewAnnex** [comment]
since you were editing your posts as I was responding I didn't see the error regarding '-ldylib1.o'. 

I don't think I have seen that before, as it looks like an issue with your xcode installation. Below are some relevant things I found googling. 

http://docs.python-guide.org/en/latest/starting/install/osx/
https://github.com/Homebrew/legacy-homebrew/issues/40762

I recommend reading through those and ensuring your xcode is properly installed with the CLI tools and then trying again.

**Comment by vancesteven** [comment]
fixing the xcode problem didn't fix the conda install problem (it still
gives the 3.4 version error although I have v4). Maybe I need to restart.
pip install worked.

thanks!

**Comment by AndrewAnnex** [comment]
the xcode problem has nothing to do with the conda install, unless it is attempting to build from source. The solution to the conda install would be to upgrade the underlying anaconda distribution to a newer release (python 3.5) as I detailed above. glad to hear you resolved your pip install issue, what was the fix you used?

**Comment by AndrewAnnex** [comment]
closing this in a day or two pending user response of fix
