### ISSUE TITLE
window creation

### ISSUE THREAD

**Issue by vancesteven** [AndrewAnnex/SpiceyPy#172]
Okay, I was able to run the Cassini example.  However, creating a window for input to gfdist isn't obvious.  Also, the c example that's the template for gfdist sends result as a pointer input.  The matlab example seems more appropriate, in which result is an output. An example would be helpful.  What are the plans for posting such "cookbooks" moving forward? I'd be happy to help as  I'm learning this stuff.

**Comment by AndrewAnnex** [comment]
So your interpretation of what gfdist does sounds a bit incorrect given my understanding. Gfdist is a void function which modifies an spice window passed in by reference. There are a number functions like this that I haven't modified to instead return a new object mainly due to lack of time/user demand. At this point it would be probably a good thing to do this, but it would be a pretty major api change resulting in a version bump to 2.0 which should probably wait until N66 is released.

Examples are available in the unit tests (test_wrapper.py). It might also be good to have examples in the docstrings for each function but with main wrapper code file already at 13k lines it might necessitate some restructuring which I haven't looked into yet. 

cookbooks have a home in the docs folder, as long as they are written in rst format they can be directly integrated into the readthedocs build just by adding them there and listing them in the index rst files.

**Comment by vancesteven** [comment]
Thanks for clarifying!
