### ISSUE TITLE
'install' does not copy into site-packages

### ISSUE THREAD

**Issue by henrythroop** [AndrewAnnex/SpiceyPy#174]
Hi --

Just a quick question about installation. New python user so maybe I'm doing something wrong here. I grabbed the code via git and then did `python setup.py install` to install it into my Anaconda / MacOS environment. After doing this, `import spiceypy` would not find the library.

I found that `install` had copied the `spiceypy-1.1.0-py3.5.egg` directory, but not `spicepy` itself. I worked around this by manually copying the `spiceypy` directory into site-packages, e.g.,

`cp -r spiceypy  /Users/throop/anaconda/envs/py3/lib/python3.5/site-packages/`

Is this how it's supposed to work?

Thanks,
Henry

**Comment by AndrewAnnex** [comment]
That shouldn't happen and my unit tests should be catching that, otherwise they would not work. That being said there is little reason to install from source, if you are using Anaconda you should follow the installation instructions here: [https://spiceypy.readthedocs.io/en/master/installation.html](https://spiceypy.readthedocs.io/en/master/installation.html)

**Comment by henrythroop** [comment]
OK, thanks for the info. I've attached a log of the install below; let me know if you need anything else. 

And by the way, I'm really stoked to have come across this library; thanks for all your work on it.

[log.txt](https://github.com/AndrewAnnex/SpiceyPy/files/616971/log.txt)

**Comment by AndrewAnnex** [comment]
thanks for the feedback, I am always glad to hear that people are finding it useful. 

looking at the log I am seeing  a section where it appears that spiceypy may have already been installed, but it doesn't necessarily have anything to do with the issue you had. I had been very sure that I successfully prevented bdist_egg from being run since I think last summer or earlier, so I will have to investigate this further.

For those coming across this issue, if you install from a pre built conda artifact you won't run into this issue, and the fix is as simple as copying the directory to your site-packages folder. While not ideal, all the other steps setuptools does appears to work except this last step.

**Comment by AndrewAnnex** [comment]
I just looked into this a bit and I wondered if you could `ls` the egg directory and let me see what wa s inside it. I just did a install on both my system python and miniconda and in both cases it does create a egg folder like this, and I am able to use spiceypy at that point. Were you not able to import spiceypy earlier?

**Comment by henrythroop** [comment]
Well, that's weird. I was trying to make you a new logfile from a clean install, and now everything seems to be working fine. Close this and I'll let you know if I ever see the issue again. (I had grabbed it from github rather than conda just out of curiosity to see the history, etc.) Anyhow, thanks.

**Comment by AndrewAnnex** [comment]
no problem
