### ISSUE TITLE
dafac (append comments to DAF) not quite there yet

### ISSUE THREAD

**Issue by drbitboy** [AndrewAnnex/SpiceyPy#209]
The interface to spiceypy.libspice.dafac_c does not work for me (Ubuntu).  This also may be a problem with some other SPICE toolkit routines that pass a single pointer to multiple strings, where the strings are embedded on the left edge of a 2-dimensional array of SpiceChars that is passed as a single block.

It's not urgent; I may fix it myself and issue a pull request.

This is what I do (cmnts is a list of <str> items):

      ### Write DAF comments
      nComments = len(cmnts)
      lenvals = max([nComments for cmnt in cmnts]) + 1

      try:  sp.dafac_c(handle,nComments,lenvals,cmnts)
      except:
        ### As of October, 2017, spiceypy.dafac_c does not work
        ### - build string and call sp.libspice.dafac_c directly
        arr = ''.join([(cmnt + ('\0'*lenvals))[:lenvals] for cmnt in cmnts])
        sp.libspice.dafac_c(handle,nComments,lenvals,arr)

P.S.  Andrew, I see you coded the HapkeModel; I met him once, I think it was in AZ.  I also coded the model in gawk.

**Comment by AndrewAnnex** [comment]
`dafac` is one of the remaining ~28 functions that have written wrappers but without any tests (see [this list](https://github.com/AndrewAnnex/SpiceyPy/wiki/Wrapper-Completion)). Functions that have no tests have not been verified and I never went back to either remove them or raise an exception or warning of some kind, which is probably the better thing to do. 

feel free to fix `dafac`, I think I do something different for other functions that are working properly with 2d char arrays, that would remove the `ncomments` and `lenvals` arguments. 

oh and I didn't code that hapkemodel, I forked someone else's repository a few years ago and they have since deleted their branch leaving me with the only copy. The git history should show the true author.

**Comment by AndrewAnnex** [comment]
I merged in the PR, thanks for the contribution! I plan to release the next version at the end of October, so your changes will be included in the pypi and anaconda distributions then.
