### ISSUE TITLE
Sincpt function in SpiceyPy returning "SpiceyPy returns not found for function: sincpt"

### ISSUE THREAD

**Issue by JustinC222** [AndrewAnnex/SpiceyPy#259]
Hey Andrew, 

Love your SpiceyPy library by the way and I'm sorry to bother you on your GitHub account. I've been struggling with this error for a couple days and was hoping you might be able to shed some light on the issue. Here's what's happening:

I'm trying to implement the Surface Intercept method within your SpiceyPy library (SpiceyPy.sincpt) and keep getting the error "Spice returns not found for function: sincpt". 

Now I know i'm using the correct amount and type of parameters in my method call and have also tried using the depracated srfxpt method (which returns the same error as sincpt). I've been using other methods within your library without error such as getfov, spkezr, utc2et, etc.. so I know that the library has been correctly imported. I've tried looking at the SpiceyPy methods for error checking just to make sure it was throwing the correct error and as I understand it (which is not well >.< ), it is and it's not just defaulting to a more generic error. You would know better than I, do you know what could be going wrong here?  

Please let me know if you need anything from me in regards to this issue, as this is my first time posting an issue, I am liable to have forgotten something. Thanks Andrew and I hope to hear from you!

**Comment by AndrewAnnex** [comment]
Sorry to say but I would just quadruple check the actual parameters you are passing to sincpt. The error indicates that spice does not find a surface intercept given the input as I think you have worked out. It would indicate to me an bad input or incomplete or wrong kernels because presumably you know there should be a surface intercept at that time and those other inputs. 

 I would recommend fiddling with the parameters like the time, look vectors and etc a bit. It might be worth going through the naif spice documentation to see a worked example of sincpt. Alternatively you could try contacting the naif with the specific kernels and code you are writing to work out what is going on.


-Andrew Annex

**Comment by JustinC222** [comment]
Thanks for the quick reply Andrew,

Just to double check, the error: "Spice returns not found for function: sincpt" is thrown when there is not a surface intercept returned at that specific et and doesn't just return false without throwing the error?

**Comment by AndrewAnnex** [comment]
Yes, spiceypy does this to make spice more python idiomatic. I added a context manager for this behavior so you can disable it at runtime if you wish see the docs link for examples

http://spiceypy.readthedocs.io/en/master/basics.html

-Andrew Annex

**Comment by JustinC222** [comment]
Ahh.. I was misinterpreting the error. I thought it was telling me that the method sincpt() was not found in the SpiceyPy library. That helps so much, thanks for being available Andrew!
