### ISSUE TITLE
Can't get full time string from trajectory file

### ISSUE THREAD

**Issue by surdahl** [AndrewAnnex/SpiceyPy#264]
Using spiceypy.etcal() to get the time string from a trajectory file, I can only get the time string to the millisecond. I'd like the full string which includes (TDB) at the end like I can see in MATLAB. Any suggestions for me?

**Comment by surdahl** [comment]
Hi @jdiazdelrio,

I have a .bsp file and I don't have an ephemeris time to turn into a string time. Assume I don't know anything about what is modeled by the file. First, I have to find the ids of the vehicles modeled in the file. I use spiceypy.spkcov to get the ids, then I use spiceypy.etcal to get the time string from the ids. The time string that I get out is not the full string you listed above, but a rounded version.

Thanks,

Sarah

**Comment by jdiazdelrio** [comment]
Hi Sarah (@surdahl),

you've got two options in order to know the coverage time. The first is to use the SPICE utility program brief. You could download it from here:

https://naif.jpl.nasa.gov/naif/utilities.html

Pic your platform and click on it. That will lead you to a page where you can download **brief**

If you want to program it yourself, then:

1.  Use spiceypy.spkobj to get the IDs codes for all the ephemeris objects in the SPK file.
2. Use spiceypy.spkcov to get the coverage window for the ephemeris object of interest within the SPK file, e.g. spiceypy.spkcov( "de405.bsp", 499, cover ). **cover** contains now the ephemeris times you are looking for. Note that it is a SPICE window, i.e. it contains start and end times for each of the coverage intervals contained within the SPK file named "de405.bsp" for the object 499 (Mars)
3. Use spiceypy.timout to retrieve the string version for each of the time boundaries, e.g. timstrs = cspice_timout( cover, 'YYYY MON DD HR:MN:SC.### (TDB) ::TDB' )

If it helps, maybe you could check the Examples section of the **spkcov** API (it seems to be exactly what you are trying to do) from the Matlab toolkit:

https://naif.jpl.nasa.gov/pub/naif/toolkit_docs/MATLAB/mice/cspice_spkcov.html

Regards,
   Jorge

**Comment by surdahl** [comment]
Jorge (@jdiazdelrio),

**Cover** does not give you ephemeris times. It gives you the time strings... Which is why I am then using spiceypy.etcal to then turn that time string to an ephemeris time. If my time string is rounded like it is, I get a different ephemeris time in seconds due to the rounding.

Sarah

**Comment by jdiazdelrio** [comment]
Hi Sarah (@surdahl),

the output of spkcov is a double precision SPICE window, named "cover".  In the Detailed_Output section on the link below, you can see that indeed, it provides you with ephemeris times:

https://naif.jpl.nasa.gov/pub/naif/toolkit_docs/C/cspice/spkcov_c.html

As it is stated there:

> The interval endpoints contained in `cover' are 
> ephemeris times, expressed as seconds past J2000 
> TDB. 

The input of etcal is also ephemeris times. See Detailed_Input below:
https://naif.jpl.nasa.gov/pub/naif/toolkit_docs/C/cspice/etcal_c.html

If you replace the call to etcal, by the call to timout, you will get as output a time string in TDB.
timstrs = cspice_timout( cover, 'YYYY MON DD HR:MN:SC.### (TDB) ::TDB' )

If what you need is only ET (ephemeris time), then you don't need any conversion. The output of spkcov is enough.

Regards,
   Jorge

**Comment by surdahl** [comment]
@jdiazdelrioI Ah okay I was translating to a time string and translating back to ephemeris time which was the problem. Thank you!
