### ISSUE TITLE
Problemn with the function spiceypy illumf

### ISSUE THREAD

**Issue by ifermion** [AndrewAnnex/SpiceyPy#267]
Hello,

I'm having a problem working with a .dsk shapemodel computing the pixel based illumination conditions. Basically, what I'm after is computing the pixel based phase angle, incident angle and emission angle.

I load the dsk file and whenever a surface pixel is illuminated I want to calculate the illumination conditions.

plate, xpt, f = spice.dskx02(handle, dladsc, haya2pos, ray)

With the above line I'm able to know if the pixel is illuminated in which case I start an if statement to calculate the angles. This is where I'm having trouble. Following are the line of code I use and the error that it results.

##############################################
if f == True :
        illu = spice.illumf('DSK/Unprioritized', RYUGU, 'SUN', et, ryugu_body_frame, 'LT+S', 'HAYABUSA2', xpt)

spiceypy.utils.support_types.SpiceyError: 
================================================================================
Toolkit version: N0066
SPICE(DSKDATANOTFOUND) --
No segments were found matching the body ID 2162173.
illumf_c --> ILLUMF --> ZZSUDSKI --> ZZDSKSPH

##############################################

I know the the dsk file is already loaded, but it does not seem to recognise in this case, which is puzzling to me. Any ideas on what's really going on or eventually some answer ?

Thank you in advance for your time.

**Comment by jdiazdelrio** [comment]
Hi there!

I think i don't have all the information needed, (what metakernel you are using to load the
data, and how you do load it), but I would guess that you are not loading the DSK through
the spice.furnsh call, and that's why the spice.illumf fails.

From what I see, you have loaded the DSK using spice.dasopr (that returns the handle you
are using for spice.dskx02). But then spice.illumf fails, which means that the data is
not loaded in the kernel pool. In order to load the data in the kernel pool, you need
to use spice.furnsh( DSK ) or spice.furnsh( meta ), and DSK provided within the meta
kernel file.

If that is not the case, please post the list of kernels you are using (or the meta-kernel)
and a snapshot of the code from the point where you load the kernels until the
illu = spice.illumf call.

I hope this helps.
Best regards,
  Jorge

Jorge Diaz del Rio
ODC Space
www.odcspace.com

**Comment by ifermion** [comment]
Many thanks for your prompt reply. I had indeed forgotten to add the dsk file in the meta kernel. This saved me a lot of time.

Best regards,
Prasanna
