### ISSUE TITLE
Silent install failure on windows 32-bit python

### ISSUE THREAD

**Issue by brhumphe** [AndrewAnnex/SpiceyPy#274]
I've had a number of confusing errors and issues trying to get this to work properly, and finally realized the problem upon reading [this comment on #250](https://github.com/AndrewAnnex/SpiceyPy/issues/250#issuecomment-360206079), which is that I had mistakenly installed a 32-bit version of Python 3.7. After switching to a 64-bit interpreter, installation worked on the first attempt.

If 32-bit is not supported, an error message saying so would be very helpful.

**Comment by AndrewAnnex** [comment]
ah I still have it listed on the readme as compatible, I will update that and look into adding an error message. thanks -Andrew

**Comment by AndrewAnnex** [comment]
I re-read this and there is no technical reason that spiceypy cannot support 32 bit installs, indeed getspice.py still downloads 32 bit cspice for windows. However getting windows builds working is very tedious, so I provide windows users the prebuilt wheels or conda-forge spiceypy distribution.

It sounds like the issue was that the errors raised during setup were not noticed or there is something wrong with the code currently, I think we have plenty of checks in the code but if you could re-run the install and send me a copy of the logs then it could be helpful to see why it was not clearly warned.
