### ISSUE TITLE
transfer the origin of instrument frame to a body fixed frame

### ISSUE THREAD

**Issue by ifermion** [AndrewAnnex/SpiceyPy#296]
Hi everyone,

I'm trying to use dskx02 function of the spiceypy toolkit to work out ray intercepts with a dsk shapemodel. I'm able to use a rotational matrix to convert vectors defined in an instrument-based reference frame in a spacecraft to a body-fixed coordinate frame for a planetary body that is being observed. However I'm having trouble converting the origin of the instrument-based coordinate system to the body-fixed coordinate frame, as this point in space is an input required as a vertex for the incoming ray/ boresight vector from the instrument.   

Perhaps I'm missing something trivial. Any inisights would be highly appreciated.

Cheers !

**Comment by jdiazdelrio** [comment]
Hi there,

normally, the origin of the instrument-based reference frame (or coordinate system) is the
spacecraft it is mounted on. Therefore, a simple call to SPKPOS or SPKEZR should give you
the vector you are looking for.

If the instrument is mounted on a platform for which an SPK exists, then the instead of using the
spacecraft name, a call to SPKPOS or SPKEZR with the instrument name would give you the origin of the reference frame your looking for (assuming you have loaded that SPK where the position of
the platform is given with respect to the spacecraft center of mass).

Note that in both cases, you should use, as reference frame for the SPKPOS/SPKEZR, the body-fixed reference frame of the planetary body that is being observed. This vector will be in the reference
frame that you're looking for, and no transformation will be required.

Cheers,
  Jorge

**Comment by ifermion** [comment]
Thanks a lot for this insight Jorge, I did discover a new functionality of the spkpos/spkezr that it can compute the position of a reference frame too, with respect to a given body.
