### ISSUE TITLE
Offline installation support

### ISSUE THREAD

**Issue by ma3oun** [AndrewAnnex/SpiceyPy#321]
If one wishes to install this package on a PC without any internet connection, offline installation fails because the setup process will try to download CSPICE anyway. Please include CSPICE files in the package for offline installation.

**Comment by AndrewAnnex** [comment]
Although I will not include CSPICE in the codebase, I did think of possibly including an environment variable override so that a user could provide the path to CSPICE source files. I may go that route, alternatively the conda-forge distribution of CSPICE and Spiceypy could be used instead.

For now this is a “won’t fix” for me
Closing #321 

-Andrew Annex
