### ISSUE TITLE
Add higher-order abstractions

### ISSUE THREAD

**Issue by GEbb4** [AndrewAnnex/SpiceyPy#417]
### Introduction
In my opinion, SpiceyPy should include a suite of more-pythonic abstractions, and this is to capture my thoughts and any subsequent discussion about that.

I propose restructuring the project into modules, in a similar fashion to many other projects (e.g. `numpy`): with an "interface" module (or possibly "core") for the actual mechanisms that wrap CSPICE, and a new "abstractions" module for higher-order functionality. And to ensure backwards compatilibily, the entire existing set of SpiceyPy functions should be mirrored in the top-level namespace (so `spiceypy.funcname()` still works). So the new directory structure would be:
```
spiceypy
+-- interface
|   +-- tests
|   |   +-- ...
|   |
|   +-- utils
|   |   +-- ...
|   |
|   +-- __init__.py
|   +-- config.py
|   +-- spiceypy.py
|
+-- abstractions
|   +-- __init__.py
|   +-- ...
|
+-- __init__.py
```
Where the top-level `__init__.py` imports all the functions from `interface.spiceypy` to preserve `spiceypy.funcname()` syntax.

### The Problem

So why do I think SpiceyPy should change scope to include more abstractions? Although SPICE is very powerful, has a huge amount of functionality, and is NASA-made and validated, it also has some shortcomings. Functions are named confusingly for new users; if I know I want to load a kernel, I search the permuted index for "LOAD" and find 8 entries, none of them called `load`, yet I find an `unload` function - users must learn that they don't want to _load_ a kernel, they want to _furnish_ their environment with it. If I want to get the radius of a body, I search the permuted index for "body" and get 27 functions, then find there are 2 functions which get body constants. I have to work out that the difference is that one accepts ID codes and the other accepts names or ID codes, then work out I don't want the `RADIUS` I want the `RADII`, and so on.

But I think the most apparent example of this is an actual piece of code I had to write recently. All I wanted to do was to check whether or not data was loaded for a given body between given times (i.e. that there was a window loaded which contained the given window). This was the code I ended up with:
```python
window = (spiceypy.str2et(start_date.isoformat()), spiceypy.str2et(end_date.isoformat()))
body_id = spiceypy.bods2c(body_name)

for idx in range(spiceypy.ktotal("SPK")):
    data = spiceypy.kdata(idx, "SPK")
    file = str(Path(data[2]).parent / data[0])
    for idcode in spiceypy.spkobj(file):
        win = spiceypy.spkcov(file, idcode)
        for j in range(spiceypy.wncard(win)):
            win_begin, win_end = spiceypy.wnfetd(win, j)
            if win_begin < window[0] and win_end > window[1] and idcode == body_id:
                return True
```
This took me about 2 hours of searching through SPICE documentation examples to write, even as someone who's been familiar with it for about a year now, and ended up being a "pythonised" version of one of the NAIF examples.

All of this is quite contrary to the [Zen of Python](https://www.python.org/dev/peps/pep-0020/) - and although SpiceyPy puts a great deal of focus on getting the "Spicey" correct, I think this would help it put more balanced focus on the "Py".

### Proposed Solution

My initial proposal, as well as the restructure described above, is for a set of 3 utility classes: `LoadedKernels`, `LoadedBodies`, and `SpiceBody`. Each of them would define suitable dunders and other methods such that they can be used pythonically to interact with SPICE, abstracting the user away from needing to know obscure function names and such.

For example, imagine wanting to check a kernel is loaded and if not, load it:
```python
if not "gm_de431.tpc" in LoadedKernels:
    LoadedKernels += "gm_de431.tpc"
    # Do something...
```
Or to access data about the sun's mean radius:
```python
sun = LoadedBodies["Sun"]
sun_mean_radius = np.mean(sun.RADII)
```
Or, consider the code above where I wanted to check that a body had data loaded between two dates:
```python
if body_name in LoadedBodies and LoadedBodies[body_name].data_between(start_date, end_date):
    # Do something...
```
This is not only much more pythonic, but much easier to read and most importantly much easier to maintain. Whilst there is a huge amount of merit to mirroring CSPICE as closely as possible, those using Python are probably using it precisely because it's more straightforward and quicker to write than C. And sure, this will take longer to execute, but probably anyone who cares enough about execution time won't be using SpiceyPy anyway, preferring faster C or FORTRAN implementations directly.

### Discussion

So what are the downsides? Obviously this adds complexity to the SpiceyPy package. Until this point, because it's passed through and handed off all responsibility for the routines and implementation to CSPICE and the user respectively, it's been able to not worry too much about either - this would change that and require a bit more rigour in testing. However, bringing that responsibility into the package only serves to make it much easier for all users to achieve what they want, with easier-to-read and easier-to-share code, and particularly for academia where SPICE is popular, that's a very appealing prospect.

There's an argument about the size of the package, but I think that's fairly null-and-void. Scientific Python packages often run to millions of lines of code and several MB of download, so I don't think it's a major issue to anyone. And because all of these features will only be _extra_, with everything else working exactly as it currently does, any arguments about changing things etc are also self-defeating. If either of these were to be a deal-breaking issue, I'd suggest that a new package be created called `spiceypy-core` which contains the core code, then these abstractions be in `spiceypy` along with a conditional import and the core as a dependency - then a hardcore user who just wants the wrapper can use `pip install spiceypy-core`, and anyone who gets spiceypy would get everything.

And whilst I've included here an initial proposal for these three classes (which I'm happy to prototype, by the way), this discussion is more about the conceptual change from SpiceyPy being a thin wrapper around CSPICE, to adding a suite of pythonic features to make the Python-CSPICE interactions as user-friendly as possible.

I know this has been quite an essay but I wanted to explain fully my views, and I'm interested to hear the opinions of other community members :-)

**Comment by mcostasitja** [comment]
@GEbb4 I believe you are proposing to cross the boundaries of what SpiceyPy is meant to be with your proposal, and implementing such abstractions could lead to confusion among the community, leading back to negative impacts to all parties, including us, the NAIF team. 

SpiceyPy is a wrapper to cspice and I believe all the SpiceyPy development efforts should be put in the Spicey rather than the Py(thonic) aspect of it. 

The SPICE Toolkit (and cspice, icy, mice, JNISpice) code is publicly available but is not open source for a reason: NASA and International flight projects are committed to using SPICE in their operations based on the understanding that it is under full control of the NAIF team. Additionally, the science community relies heavily on the robustness of the SPICE software to enable scientific discovery. 

Adding such Pythonic abstractions would make SpiceyPy deviate from cspice in such a way that most probably we, NAIF, would have trouble endorsing, supporting, and recommending it as we have done until today.

I would suggest you to propose starting a new package with such abstractions.

**Comment by AndrewAnnex** [comment]
Initially SpiceyPy was started to become the python equivalent to NAIF provided MICY and ICY wrappers, a goal that SpiceyPy has succeeded at and has provided immense value to the community and in particular to those converting existing matlab/idl scripts to python.

I chose this scope for spiceypy because I have never been funded for any of the work I did on this project, and I had no idea how far I would take it. 

I think some of these higher level interfaces would be useful but I disagree with the proposed restructuring of spiceypy as it would be a massive breaking API change, could break backwards compatibility of user's code, and is also unnecessary.

SpiceyPy could remain "the core" without this restructuring and all of these higher level interfaces could exist in a new submodule within spiceypy or within the existing utils module. 

That said, there are other models that could be followed. Some larger libraries have a "contrib" package that depends on the original library which allows decoupling of the releases/delegated maintenance. Functionally, this is equivalent to making an new independent package, but by making a "spiceypy-contrib" it would make it easier to advertise/coordinate. 

And of course anyone is free to make/maintain their own package, a goal of spiceypy that I've stated in previous conference talks has been to allow community members to make their own higher level interfaces.

Of the options above, I think I am more attracted to the idea of a new contrib package, because it would allow that project to remain unstable for a period while the api is finalized, and users would have to "opt-in" to use it by explicitly installing it.  

@mcostasitja's point is important to consider as well in this context about including the abstractions in the main library even with the different structuring I suggest. By making a contrib project, it would at least be 1 step separated from users who may not know that the provided interfaces are not NAIF origin. I know I've slightly bent this case in a few places with some user contributed utilities, but maybe this is another argument for making a contrib project to capture those additions.

**Comment by jessemapel** [comment]
I would second @mcostasitja and @AndrewAnnex to keep spiceypy as a thin wrapper around existing SPICE routines. Things like automatically vectorizing and better return setups make sense to me, but I'd probably draw the line around #413. It wraps two functions (furnsh and unload) in a Pythonic way, but it doesn't provide any higher level interface.

What you are proposing would be useful for the community, but it sounds like a new package that is dependent upon SpiceyPy or a contributing pacakge as @AndrewAnnex suggested.

**Comment by GEbb4** [comment]
Given all that's been said here, I can see the merit in a second package as suggested by @AndrewAnnex . Endorsement/support (or whatever term is most appropriate) from NAIF is clearly important for the package, and if creating a `-contrib` package is what's needed for that to continue, then that's the correct course of action.

Based on what @mcostasitja says, and slightly contrary to what @jessemapel suggests, I'd say that #413 should probably be left hanging here and instead feature in the new package, along with other abstractions. This avoids ambiguity of scope - `spiceypy` is very specifically just a python wrapper (with some vectorisation) for SPICE, otherwise mirroring it, and `spiceypy-contrib` is anything else.

**Comment by AndrewAnnex** [comment]
@GEbb4 I think from the discussion above that #413 can live inside spiceypy but if you want to use it to help give shape to spiceypy-contrib then feel free to close the pr or let me know if I can close it. 

As for starting spiceypy-contrib, I want to think a bit more about where it should live (under my account or under planetarypy or as a module in planetarypy.core). @GEbb4 if you want to get started on making the api you lay out above on your own then feel free to do so, just as long as you don't use the name `spiceypy-contrib`. Because the name is closely associated with me, some people may end up contacting me directly about it if you use the name and make the project without me, even if you make it clear that you are the author. I don't really have the motivation/free time at the moment to implement a full high level API that I fully support, but feel free to ask me to review PRs as you make progress. 

However, if you would prefer, once I have some time to think more about where the project should live I should be able to find some time to at least make a skeleton spiceypy-contrib that you could then submit PRs to. That said, I may allow myself to decide to call that package something else entirely to keep the boundaries clearer as well.

**Comment by AndrewAnnex** [comment]
For now, I am closing this issue with the consensus opinion that much of the proposal is out of scope for spiceypy. Feel free to reopen if further debate is needed on this topic
